package handlers

import "testing"

// TestSafeRedirectTargetAllowsSameSitePaths verifies that ordinary
// same-site relative paths (with or without a query string) pass through
// unchanged, since this is the normal case generated by
// helpers.BindLangData for the language-toggle link.
func TestSafeRedirectTargetAllowsSameSitePaths(t *testing.T) {
	cases := map[string]string{
		"/dashboard":                  "/dashboard",
		"/dashboard/suppliers":        "/dashboard/suppliers",
		"/dashboard/suppliers?q=acme": "/dashboard/suppliers?q=acme",
	}
	for in, want := range cases {
		if got := safeRedirectTarget(in); got != want {
			t.Errorf("safeRedirectTarget(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestSafeRedirectTargetBlocksOpenRedirect verifies every known
// open-redirect bypass shape falls back to "/dashboard" instead of
// reaching http.Redirect with attacker-controlled off-site content.
func TestSafeRedirectTargetBlocksOpenRedirect(t *testing.T) {
	cases := []string{
		"",
		"https://evil.example",
		"http://evil.example/phish",
		"//evil.example",      // protocol-relative
		"///evil.example",     // extra-slash variant
		"/\\evil.example",     // backslash browsers normalize to //
		"evil.example",        // no leading slash at all
		"javascript:alert(1)", // non-http scheme
	}
	for _, in := range cases {
		if got := safeRedirectTarget(in); got != "/dashboard" {
			t.Errorf("safeRedirectTarget(%q) = %q, want fallback %q (open-redirect not blocked)", in, got, "/dashboard")
		}
	}
}
